#!/bin/bash

# /etc/init.d/jira
### BEGIN INIT INFO
# Provides:          jira
# Required-Start:    $remote_fs $syslog $mysql
# Required-Stop:     $remote_fs $syslog $mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

set -e

case "${1:-''}" in

  'start')
        sudo -u jira /home/jira/jira/atlassian-jira-software-7.6.2-standalone/bin/start-jira.sh
  ;;

  'stop' | 'restart')
        sudo -u jira /home/jira/jira/atlassian-jira-software-7.6.2-standalone/bin/stop-jira.sh
  ;;

  *)
  echo "Accepted arguments: start|stop"
  exit 1
  ;;
esac
